name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t amazon_pet -f Dockerfile .
      
    - name: Generate Deployment Package
      run: zip -r deploy.zip requirements.txt Dockerfile app/

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Pet review classifier (amazon)
        environment_name: Petreviewclassifieramazon-env
        version_label: "pet review classifier 3000"
        region: eu-west-2
        deployment_package: deploy.zip
